// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playground.EF.Core.Infrastructure.Persistence;

#nullable disable

namespace Playground.EF.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241229013241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Playground.EF.Core.Domain.Entities.Abstracts.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Producto_Nombre");

                    b.ToTable("TBL_PRODUCTS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "32D8D70C-77E8-41B1-B249-73EE7A747E6A",
                            Name = "Teclado",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = "180435F8-D7DB-4230-8B9E-5B5298929F00",
                            Name = "Mouse",
                            Price = 10.50m
                        },
                        new
                        {
                            Id = "977C49D1-62CA-4B6E-9848-1B1A989EA8BB",
                            Name = "Monitor",
                            Price = 199.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
